import Nav from "@/components/Nav";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import { useRef, useState } from "react";
interface FormData {
  target: {
    resumeFile: File;
  };
}

export function PillList({ list }: { list: string[] }) {
  return (
    <div className={styles.pillList}>
      {list.map((entry: string) => {
        return <span className={styles.pill}>{entry} </span>;
      })}
    </div>
  );
}

export default function Home() {
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const fileUploadRef = useRef<HTMLInputElement>(null);
  const [results, setResults] = useState<any>({
    skills: ["html", "css"],
    education: ["class of 2024"],
    experience: [],
    roles: [],
  });

  const handleSubmit = async (e: React.SyntheticEvent) => {
    e.preventDefault();
  };

  return (
    <>
      <Head>
        <title>LinkedOut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <div className={styles.section}>
          <div className={styles.form}>
            <h2>Upload Resume</h2>
            <form onSubmit={handleSubmit}>
              <input
                ref={fileUploadRef}
                className={styles.input}
                id="resumeFile"
                type="file"
                accept=".pdf"
              ></input>
              <button className={styles.submitButton}>Search</button>
            </form>
          </div>
          <div className={styles.resumePreview}>
            <h2>Data Gathered</h2>
            {results ? (
              <>
                <p>Resume File: {uploadedFile?.name}</p>
                <br />
                <h3>Skills</h3>
                <PillList list={results.skills} />
              </>
            ) : null}
          </div>
        </div>
        <div className={styles.section}>
          <div className={styles.jobsList}>
            <h2>Matched Jobs</h2>
            <br />
            <div className={styles.jobListing}>
              <div>
                <h3>Job Title</h3>
                <p>Company</p>
                <p>Location</p>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.section}>
          <div className={styles.jobsList}>
            <h2>Job Details</h2>
          </div>
        </div>
      </main>
    </>
  );
}
